services:
  # 啟動3個mongo container用以建置Replica Set
  KiwiRS-mongo1:
    hostname: KiwiRS-mongo1
    image: mongo:${MONGO_IMAGE_VERSION}
    expose:
      - 27017
    ports:
      - ${MONGO1_HOST_PORT}:27017
    restart: always
    command: mongod --replSet my-mongo-set
  KiwiRS-mongo2:
    hostname: KiwiRS-mongo2
    image: mongo:${MONGO_IMAGE_VERSION}
    expose:
      - 27017
    ports:
      - ${MONGO2_HOST_PORT}:27017
    restart: always
    command: mongod --replSet my-mongo-set
  KiwiRS-mongo3:
    hostname: KiwiRS-mongo3
    image: mongo:${MONGO_IMAGE_VERSION}
    expose:
      - 27017
    ports:
      - ${MONGO3_HOST_PORT}:27017
    restart: always
    command: mongod --replSet my-mongo-set

  # 初始化Mongo Replica Server
  mongoinit:
    image: mongo:${MONGO_IMAGE_VERSION}
    # 這個container只會執行一次
    restart: "on-failure"
    depends_on:
      - KiwiRS-mongo1
      - KiwiRS-mongo2
      - KiwiRS-mongo3
    command: >
      mongo --host KiwiRS-mongo1:27017 --eval  ' config = { "_id" : "my-mongo-set", "members" : [
        {
          "_id" : 0,
          "host" : "KiwiRS-mongo1:27017"
        },
        {
          "_id" : 1,
          "host" : "KiwiRS-mongo2:27017"
        },
        {
          "_id" : 2,
          "host" : "KiwiRS-mongo3:27017"
        }
      ] }; rs.initiate(config); '
